.TH AMP-UDPSTREAM 8 "2016-09-20" "amplet2-client" "The Active Measurement Project"

.SH NAME
amp-udpstream \- AMP standalone UDP jitter test


.SH SYNOPSIS
\fBamp-udpstream\fR \fB-s\fR [\fIoptions\fR]
.br
\fBamp-udpstream\fR \fB-c \fIserver\fR [\fIoptions\fR]


.SH DESCRIPTION
\fBamp-udpstream\fP is the standalone version of the \fBamplet2\fP(8)
UDP jitter test. It sends streams of UDP packets between two endpoints (either
one being this standalone test or a running instance of \fBamplet2\fP(8)) and
reports on the jitter, latency and loss observed. These values can be used
to calculate Mean Opinion Scores for possible Voice Over IP streams.


.SH GENERAL OPTIONS
.TP
\fB-p, --port \fIport\fR
Set server control port to connect to/listen on to be \fIport\fR. The default is 8815.


.TP
\fB-I, --interface \fIiface\fR
Specifies the interface (device) that tests should use when sending packets.
By default the interface will be selected according to the routing table.


.TP
\fB-4, --ipv4 \fIa.b.c.d\fR
Specifies the source IPv4 address that tests should use when sending packets to
IPv4 targets. This address must belong to one of the interfaces.
By default the IPv4 address of the outgoing interface will be used.


.TP
\fB-6, --ipv6 \fIa:b:c:d:e:f:g:h\fR
Specifies the source IPv6 address that tests should use when sending packets to
IPv6 targets. This address must belong to one of the interfaces.
By default the IPv6 address of the outgoing interface will be used.


.SH SERVER OPTIONS
.TP
\fB-s, --server\fR
Run in server mode.


.SH CLIENT OPTIONS
.TP
\fB-c, --client \fIhost\fR
Run in client mode, connecting to \fIhost\fR.


.TP
\fB-d, --direction \fIdir\fR
Magic value describing direction. Valid values are 0 (client to server),
1 (server to client), 2 (client to server then server to client),
3 (server to client then client to server). The default is 2.


.TP
\fB-D, --delay \fIusec\fR
Delay between sending consecutive packets in the stream. The default is
20000usec (20ms).


.TP
\fB-n, --packet-count \fIcount\fR
Number of packets to send in the stream. The default is 11.


.TP
\fB-P, --test-port \fIport\fR
Perform the actual throughput test using port \fIport\fR. The default is 8816.


.TP
\fB-Q, --dscp \fIcodepoint\fR
IP differentiated services codepoint to set. This should be a string
representing a 6-bit value in binary, octal, decimal or hexadecimal, or the
short name of a predefined, commonly used codepoint.


.TP
\fB-r, --rtt-samples \fIN\fR
Reflect every \fIN\fRth probe packet to provide an estimate of the round trip
time. At large packet volumes or with low delay between packets, you may want
to lower this to reduce load on the network and/or hosts. The default is to use
every packet.


.TP
\fB-z, --packet-size \fIbytes\fR
Specifies the total number of bytes to be sent per packet (including headers).
The default is 100 bytes.


.SH MISCELLANEOUS OPTIONS
.TP
\fB-h, --help\fR
Show summary of options.


.TP
\fB-v, --version\fR
Show version of program.


.TP
\fB-x, --debug\fR
Enable extra debugging output.


.SH EXAMPLES
.TP
\fBamp-udpstream -c \fI<target>\fB -d 1 -D 10000\fR
Run a server to client test with 10ms between packets in the stream.


.TP
\fBamp-udpstream -c \fI<target>\fB -d 3 -n 1000 -r 2\fR
Run a server to client test, then a client to server test, both streams having
1000 packets, using every second packet as an RTT estimate.


.SH SEE ALSO
.BR amplet2 (8),
.BR amplet2-remote (8),
.BR amp-icmp (8),
.BR amp-trace (8),
.BR amp-dns (8),
.BR amp-throughput (8),
.BR amp-http (8),
.BR amp-tcpping (8).


.SH AUTHOR
amp-udpstream was written by Brendon Jones <brendonj@waikato.ac.nz>.

.PP
This manual page was written by Brendon Jones <brendonj@waikato.ac.nz>.
