.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH AMP-TCPPING 8 "Jul 24, 2014" "amplet2-client" "The Active Measurement Project"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
amp-tcpping \- AMP standalone TCP SYN latency test
.SH SYNOPSIS
\fBamp-tcpping\fR [\fB-hrx\fR] [\fB-P \fIportnumber\fB\fR] [\fB-p \fImilliseconds\fB\fR] [\fB-s \fIpacketsize\fB\fR] [\fB-I \fIiface\fB\fR] [\fB-4 \fIaddress\fB\fR] [\fB-6 \fIaddress\fB\fR] -- \fIdestination1\fR [\fIdestination2\fR \fI...\fR]
.SH DESCRIPTION
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBamp-tcpping\fP is the standalone version of the \fBamplet2\fP(8)
TCP Ping test. It attempts to measure latency by sending a TCP SYN packet
to a destination and waiting for a response (which might be a SYN ACK, a RST
or an ICMP error). This test is particularly useful for measuring latency
for paths where ICMP is blocked or rate-limited. Like the AMP ICMP test, this
test can measure latency for multiple destinations simultaneously. All 
destinations listed on the command line will be tested to. Any destinations
that are hostnames will be resolved and every address that the name resolves
to will be tested.

.SH OPTIONS
.TP
\fB-h, --help\fR
Show summary of options.
.TP
\fB-I, --interface \fIiface\fB\fR
Specifies the interface (device) that tests should use when sending packets.
By default the interface will be selected according to the routing table.
.TP
\fB-P, --port \fIportnumber\fB\fR
The destination port number to send the SYN packets to. The default port 
number is 80 (i.e. the www port).
.TP
\fB-p, --perturbate \fImilliseconds\fB\fR
Delay the test by a random number of milliseconds, up to a maximum of \fImilliseconds\fR. The default is to not perturbate tests (no delay).
.TP
\fB-r, --random\fR
Use a random packet size for each test.
.TP
\fB-s, --size \fIpacketsize\fB\fR
Specifies the total number of bytes to be sent per packet (including headers).
The default is 84 bytes.
.TP
\fB-v, --version\fR
Show version of program.
.TP
\fB-x, --debug\fR
Enable extra debugging output.
.TP
\fB-4, --ipv4 \fIa.b.c.d\fB\fR
Specifies the source IPv4 address that tests should use when sending packets to
IPv4 targets. This address must belong to one of the interfaces.
By default the IPv4 address of the outgoing interface will be used.
.TP
\fB-6, --ipv6 \fIa:b:c:d:e:f:g:h\fB\fR
Specifies the source IPv6 address that tests should use when sending packets to
IPv6 targets. This address must belong to one of the interfaces.
By default the IPv6 address of the outgoing interface will be used.

.SH SEE ALSO
.BR amplet2 (8),
.BR amp-icmp (8),
.BR amp-trace (8),
.BR amp-dns (8),
.BR amp-throughput (8),
.BR amp-http (8).

.SH SECURITY
\fBamp-tcpping\fR requires raw socket access to run.
.\" CAP_NET_RAWIO, see man ping

.SH AUTHOR
amp-tcpping was written by Shane Alcock <salcock@waikato.ac.nz>.
.PP
This manual page was written by Shane Alcock <salcock@waikato.ac.nz>,
for the Debian project (and may be used by others).
