.TH AMP-DNS 8 "2019-07-02" "amplet2-client" "The Active Measurement Project"

.SH NAME
amp-dns \- AMP standalone DNS lookup test


.SH SYNOPSIS
\fBamp-dns\fR [\fB-hnrsx\fR] [\fB-p \fImilliseconds\fR] [\fB-c \fIclass\fR] [\fB-t \fItype\fR] [\fB-z \fIsize\fR] [\fB-I \fIiface\fR] [\fB-4 \fIaddress\fR] [\fB-6 \fIaddress\fR] [\fB-Q \fIcodepoint\fR] [\fB-Z \fImicroseconds\fR] \fB-q \fIquery\fR -- \fIdestination1\fR [\fIdestination2\fR \fI...\fR]


.SH DESCRIPTION
\fBamp-dns\fP is the standalone version of the \fBamplet2\fP(8)
DNS lookup test. It is very similar in function to \fBdig\fR(1),
except that it can
test to multiple destinations simultaneously. All destinations listed on the
command line will be tested to. Any destinations that are hostnames will be
resolved, and every address that they resolve to will be tested.


.SH OPTIONS
.TP
\fB-c, --class \fIclass\fR
Specifies the class of record that should be queried. Accepts the decimal
value of any valid class, or IN for Internet. The default is IN.


.TP
\fB-h, --help\fR
Show summary of options.


.TP
\fB-I, --interface \fIiface\fR
Specifies the interface (device) that tests should use when sending packets.
By default the interface will be selected according to the routing table.



.TP
\fB-n, --nsid\fR
Include an EDNS name server ID request when sending the query. Off by default.


.TP
\fB-p, --perturbate \fImilliseconds\fR
Delay the test by a random number of milliseconds, up to a maximum of \fImilliseconds\fR. The default is to not perturbate tests (no delay).


.TP
\fB-Q, --dscp \fIcodepoint\fR
IP differentiated services codepoint to set. This should be a string
representing a 6-bit value in binary, octal, decimal or hexadecimal, or the
short name of a predefined, commonly used codepoint.


.TP
\fB-q, --query \fIquery\fR
The query name to ask the server about.


.TP
\fB-r, --recurse\fR
Enable recursion for this query. Off by default.


.TP
\fB-s, --dnssec\fR
Request that DNSSEC records be sent. Off by default.


.TP
\fB-t, --type \fItype\fR
Specifies the type of record that should be queried. Accepts the decimal
value of any valid type, or one of A, NS, AAAA, PTR, MX, SOA, ANY.
The default is A.


.TP
\fB-v, --version\fR
Show version of program.


.TP
\fB-x, --debug\fR
Enable extra debugging output.


.TP
\fB-Z, --interpacketgap \fImicroseconds\fR
Minimum number of microseconds between sending probe/query packets.


.TP
\fB-z, --payload \fIsize\fR
Specifies the UDP payload buffer size for DNSSEC or NSID messages. The default
is 4096.


.TP
\fB-4, --ipv4 \fIa.b.c.d\fR
Specifies the source IPv4 address that tests should use when sending packets to
IPv4 targets. This address must belong to one of the interfaces.
By default the IPv4 address of the outgoing interface will be used.


.TP
\fB-6, --ipv6 \fIa:b:c:d:e:f:g:h\fR
Specifies the source IPv6 address that tests should use when sending packets to
IPv6 targets. This address must belong to one of the interfaces.
By default the IPv6 address of the outgoing interface will be used.


.SH SEE ALSO
.BR amplet2 (8),
.BR amplet2-remote (8),
.BR amp-icmp (8),
.BR amp-trace (8),
.BR amp-throughput (8),
.BR amp-http (8),
.BR amp-tcpping (8),
.BR amp-udpstream (8),
.BR amp-youtube (8),
.BR amp-fastping (8),
.BR amp-external (8).

.SH AUTHOR
amp-dns was written by Brendon Jones <brendonj@waikato.ac.nz>.

.PP
This manual page was written by Brendon Jones <brendonj@waikato.ac.nz>.
