.TH AMPLET2-REMOTE 8 "2016-09-20" "amplet2-client" "The Active Measurement Project"

.SH NAME
amplet2-remote \- AMP client remote control


.SH SYNOPSIS
\fBamplet2-remote\fR [\fB-hlx\fR] \fB-c \fIhost\fR \fB-t \fItest\fR \fB--cacert \fIfile\fR \fB--cert \fIfile\fR \fB--key \fIfile\fR [\fB-p \fIport\fR] [\fB-I \fIiface\fR] [\fB-4 \fIaddress\fR] [\fB-6 \fIaddress\fR] [\fB-a \fIarguments\fR] -- \fIdestination1\fR [\fIdestination2\fR \fI...\fR]


.SH DESCRIPTION
\fBamplet2-remote\fP can be used to connect to a running \fBamplet2\fP process
and trigger tests to be run remotely. All destinations listed on the
command line will be passed to the specified test. Any destinations that are
hostnames will be resolved by the remote client.

\fBamplet2\fP only accepts secure connections, you must specify \fB--cacert\fP,
\fB--cert\fP and \fB--key\fP with appropriate credentials that will be trusted.


.SH OPTIONS
.TP
\fB-a, --args \fIarguments\fR
A quoted string of all the arguments that should be passed through to the test
being run on the remote \fBamplet2\fP process.


.TP
\fB-c, --connect \fIhost\fR
Connect to the \fBamplet2\fP process running on \fIhost\fR.


.TP
\fB--cacert \fIfile\fR
Use the specified \fIfile\fR as the trusted CA certificate.


.TP
\fB--cert \fIfile\fR
Use the specified \fIfile\fR as the certificate to present when connecting to
the remote \fBamplet2\fP process. The certificate should be in PEM format.


.TP
\fB-h, --help\fR
Show summary of options.


.TP
\fB-I, --interface \fIiface\fR
Specifies the interface (device) that tests should use when sending packets.
By default the interface will be selected according to the routing table.


.TP
\fB--key \fIfile\fR
Use the specified \fIfile\fR as the private key when connecting to
the remote \fBamplet2\fP process. The key should be in PEM format.


.TP
\fB-l, --list\fR
List all the available tests that this program (but not necessarily the remote
client!) understands.


.TP
\fB-p, --port \fIport\fR
Connect to the \fBamplet2\fP control socket on port \fIport\fR. The default is
8869.


.TP
\fB-t, --test \fItest\fR
Run \fItest\fR on the remote \fBamplet2\fP process. Use \fB-l\fP to see all
available tests that this program (but not necessarily the remote client!)
understands.


.TP
\fB-x, --debug\fR
Enable extra debugging output.


.TP
\fB-4, --ipv4 \fIa.b.c.d\fR
Specifies the source IPv4 address that tests should use when sending packets to
IPv4 targets. This address must belong to one of the interfaces.
By default the IPv4 address of the outgoing interface will be used.


.TP
\fB-6, --ipv6 \fIa:b:c:d:e:f:g:h\fR
Specifies the source IPv6 address that tests should use when sending packets to
IPv6 targets. This address must belong to one of the interfaces.
By default the IPv6 address of the outgoing interface will be used.


.SH SEE ALSO
.BR amplet2 (8),
.BR amp-icmp (8),
.BR amp-trace (8),
.BR amp-dns (8),
.BR amp-throughput (8),
.BR amp-http (8),
.BR amp-tcpping (8),
.BR amp-udpstream (8).


.SH AUTHOR
amplet2-remote was written by Brendon Jones <brendonj@waikato.ac.nz>.

.PP
This manual page was written by Brendon Jones <brendonj@waikato.ac.nz>.
